import{a as L,S as b,i as a}from"./assets/vendor-95dc692e.js";(function(){const s=document.createElement("link").relList;if(s&&s.supports&&s.supports("modulepreload"))return;for(const t of document.querySelectorAll('link[rel="modulepreload"]'))n(t);new MutationObserver(t=>{for(const o of t)if(o.type==="childList")for(const u of o.addedNodes)u.tagName==="LINK"&&u.rel==="modulepreload"&&n(u)}).observe(document,{childList:!0,subtree:!0});function e(t){const o={};return t.integrity&&(o.integrity=t.integrity),t.referrerPolicy&&(o.referrerPolicy=t.referrerPolicy),t.crossOrigin==="use-credentials"?o.credentials="include":t.crossOrigin==="anonymous"?o.credentials="omit":o.credentials="same-origin",o}function n(t){if(t.ep)return;t.ep=!0;const o=e(t);fetch(t.href,o)}})();async function m(r,s){const e="https://pixabay.com/api/",n={key:"43075807-09317d918fe027bf1568df9fe",q:r,image_type:"photo",orientation:"horizontal",safesearch:!0,per_page:15,page:s};return(await L.get(e,{params:n})).data}const w=new b("ul.gallery a",{captionsData:"alt"}),S=document.querySelector("ul.gallery");function p(r){if(r.length==0)iziToast.error({title:"Error",message:"❌ Sorry, there are no images matching your search query. Please, try again!",theme:"dark",progressBarColor:"#FFFFFF",color:"#EF4040",position:"topRight"});else{const s=r.map(e=>`<li class="photos-list-item">
        <a class="photos-list-link" href="${e.largeImageURL}">
        <img class="photo" src="${e.webformatURL}" alt="${e.tags}"/>
        </a>
        <ul class="photo-information-container">
        <li class="item-photo-information-container"><p><span class="accent">Likes</span></br>${e.likes}</p></li>
        <li class="item-photo-information-container"><p><span class="accent">Views</span></br>${e.views}</p></li>
        <li class="item-photo-information-container"><p><span class="accent">Comments</span></br>${e.comments}</p></li>
        <li class="item-photo-information-container"><p><span class="accent">Downloads</span></br>${e.downloads}</p></li>
        </ul>
        </li>`).join("");S.insertAdjacentHTML("beforeend",s),w.refresh()}}document.querySelector("input");const f=document.querySelector("form"),h=document.querySelector(".loader"),P=document.querySelector("ul.gallery"),d=document.querySelector(".btn-load-more");let q,i=1,g=0;const v=15;function M(){h.classList.remove("hidden")}function c(){h.classList.add("hidden")}function R(){d.classList.remove("hidden")}function l(){d.classList.add("hidden")}c();f.addEventListener("submit",$);async function $(r){r.preventDefault(),l(),M(),P.innerHTML="",i=1;const s=r.target.elements.search.value.trim();if(!s){a.show({message:"Please complete the field!",position:"topRight"}),c();return}try{const e=await m(s,i);g=Math.ceil(e.totalHits/v),e.hits.length===0?a.error({message:"❌Sorry, there are no images matching your search query. Please try again!",position:"topRight"}):(p(e.hits),y())}catch{a.error({message:"Sorry, an error occurred while loading. Please try again!",position:"topRight"})}c(),f.reset()}d.addEventListener("click",F);async function F(){i+=1,l();try{const r=await m(q,i);p(r.hits),R()}catch{a.error({message:"Sorry, an error occurred while loading. Please try again!",position:"topRight"})}c(),y()}function y(){i>=g?(l(),a.info({message:"We're sorry, but you've reached the end of search results.",position:"topRight"})):l()}
//# sourceMappingURL=commonHelpers.js.map
