import{a as w,S,i as a}from"./assets/vendor-95dc692e.js";(function(){const t=document.createElement("link").relList;if(t&&t.supports&&t.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))n(e);new MutationObserver(e=>{for(const s of e)if(s.type==="childList")for(const d of s.addedNodes)d.tagName==="LINK"&&d.rel==="modulepreload"&&n(d)}).observe(document,{childList:!0,subtree:!0});function o(e){const s={};return e.integrity&&(s.integrity=e.integrity),e.referrerPolicy&&(s.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?s.credentials="include":e.crossOrigin==="anonymous"?s.credentials="omit":s.credentials="same-origin",s}function n(e){if(e.ep)return;e.ep=!0;const s=o(e);fetch(e.href,s)}})();async function f(r,t){const o="https://pixabay.com/api/",n={key:"43075807-09317d918fe027bf1568df9fe",q:r,image_type:"photo",orientation:"horizontal",safesearch:!0,per_page:15,page:t};return(await w.get(o,{params:n})).data}const P=new S("ul.gallery a",{captionsData:"alt"}),q=document.querySelector("ul.gallery");function h(r){if(r.length==0)iziToast.error({title:"Error",message:"❌ Sorry, there are no images matching your search query. Please, try again!",theme:"dark",progressBarColor:"#FFFFFF",color:"#EF4040",position:"topRight"});else{const t=r.map(o=>`<li class="photos-list-item">
        <a class="photos-list-link" href="${o.largeImageURL}">
        <img class="photo" src="${o.webformatURL}" alt="${o.tags}"/>
        </a>
        <ul class="photo-information-container">
        <li class="item-photo-information-container"><p><span class="accent">Likes</span></br>${o.likes}</p></li>
        <li class="item-photo-information-container"><p><span class="accent">Views</span></br>${o.views}</p></li>
        <li class="item-photo-information-container"><p><span class="accent">Comments</span></br>${o.comments}</p></li>
        <li class="item-photo-information-container"><p><span class="accent">Downloads</span></br>${o.downloads}</p></li>
        </ul>
        </li>`).join("");q.insertAdjacentHTML("beforeend",t),P.refresh()}}document.querySelector("input");const g=document.querySelector("form"),y=document.querySelector(".loader"),v=document.querySelector("ul.gallery"),m=document.querySelector(".btn-load-more");let c="",i=1,L=0;const M=15;l();u();g.addEventListener("submit",R);async function R(r){if(r.preventDefault(),v.innerHTML="",i=1,c=r.target.elements.search.value.trim(),!c){a.show({message:"Please complete the field!",position:"topRight"}),l();return}try{const t=await f(c,i);L=Math.ceil(t.totalHits/M),t.hits.length===0?(a.error({message:"❌Sorry, there are no images matching your search query. Please try again!",position:"topRight"}),u()):(h(t.hits),b(),F())}catch{a.error({message:"Sorry, an error occurred while loading. Please try again!",position:"topRight"})}l(),g.reset()}m.addEventListener("click",$);async function $(){i+=1,p();try{const r=await f(c,i);h(r.hits),p()}catch{a.error({message:"Sorry, an error occurred while loading. Please try again!",position:"topRight"})}l(),b()}function b(){i>=L&&a.info({message:"We're sorry, but you've reached the end of search results.",position:"topRight"}),u()}function p(){y.classList.remove("hidden")}function l(){y.classList.add("hidden")}function F(){m.classList.remove("hidden")}function u(){m.classList.add("hidden")}
//# sourceMappingURL=commonHelpers.js.map
