import{a as L,S as b,i as a}from"./assets/vendor-95dc692e.js";(function(){const t=document.createElement("link").relList;if(t&&t.supports&&t.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))c(e);new MutationObserver(e=>{for(const s of e)if(s.type==="childList")for(const d of s.addedNodes)d.tagName==="LINK"&&d.rel==="modulepreload"&&c(d)}).observe(document,{childList:!0,subtree:!0});function o(e){const s={};return e.integrity&&(s.integrity=e.integrity),e.referrerPolicy&&(s.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?s.credentials="include":e.crossOrigin==="anonymous"?s.credentials="omit":s.credentials="same-origin",s}function c(e){if(e.ep)return;e.ep=!0;const s=o(e);fetch(e.href,s)}})();async function p(r,t){const o="https://pixabay.com/api/",c={key:"43075807-09317d918fe027bf1568df9fe",q:r,image_type:"photo",orientation:"horizontal",safesearch:!0,per_page:15,page:t};return(await L.get(o,{params:c})).data}const S=new b("ul.gallery a",{captionsData:"alt"}),w=document.querySelector("ul.gallery");function f(r){if(r.length==0)iziToast.error({title:"Error",message:"❌ Sorry, there are no images matching your search query. Please, try again!",theme:"dark",progressBarColor:"#FFFFFF",color:"#EF4040",position:"topRight"});else{const t=r.map(o=>`<li class="photos-list-item">
        <a class="photos-list-link" href="${o.largeImageURL}">
        <img class="photo" src="${o.webformatURL}" alt="${o.tags}"/>
        </a>
        <ul class="photo-information-container">
        <li class="item-photo-information-container"><p><span class="accent">Likes</span></br>${o.likes}</p></li>
        <li class="item-photo-information-container"><p><span class="accent">Views</span></br>${o.views}</p></li>
        <li class="item-photo-information-container"><p><span class="accent">Comments</span></br>${o.comments}</p></li>
        <li class="item-photo-information-container"><p><span class="accent">Downloads</span></br>${o.downloads}</p></li>
        </ul>
        </li>`).join("");w.insertAdjacentHTML("beforeend",t),S.refresh()}}document.querySelector("input");const g=document.querySelector("form"),P=document.querySelector(".loader"),q=document.querySelector("ul.gallery"),m=document.querySelector(".btn-load-more");let l="",i=1,h=0;const M=15;v();n();g.addEventListener("submit",R);async function R(r){if(r.preventDefault(),q.innerHTML="",i=1,l=r.target.elements.search.value.trim(),!l){a.show({message:"Please complete the field!",position:"topRight"}),n();return}try{const t=await p(l,i);h=Math.ceil(t.totalHits/M),t.hits.length===0?a.error({message:"❌Sorry, there are no images matching your search query. Please try again!",position:"topRight"}):(f(t.hits),y(),n())}catch{a.error({message:"Sorry, an error occurred while loading. Please try again!",position:"topRight"})}u(),g.reset()}m.addEventListener("click",$);async function $(){i+=1,n();try{const r=await p(l,i);f(r.hits),u()}catch{a.error({message:"Sorry, an error occurred while loading. Please try again!",position:"topRight"})}u(),y()}function y(){i>=h?(u(),a.info({message:"We're sorry, but you've reached the end of search results.",position:"topRight"})):n()}function v(){P.classList.add("hidden")}function u(){m.classList.remove("hidden")}function n(){m.classList.add("hidden")}
//# sourceMappingURL=commonHelpers.js.map
